# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.1
    hooks:
      - id: ruff
        args:
          - --fix
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
        - id: codespell
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
        - id: mypy
